### ISSUE TITLE
PROJECT PROPOSAL - Emotion Detection from Text

### ISSUE THREAD

**Issue by Ank1taS** [CognitiveLab-tech/World-of-AI#125]
## Emotion Detection from Text
A model will predict the emotion behind a sentence i.e model will take a sentence or group of statements and classify it to a specific emotion class

---
| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Using a dataset available on the Kaggle  ML model will predict the emotion/ state of mind of the writer who wrote the text segment.|
| Github | Ank1taS                 |
| Email  |  sahoosona2209@gmail.com          |
| Label  | Project Request                   |

https://github.com/Ank1taS
---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Emotion Detection from Text

## Description
This ML model will take a sentence or group of statements and classify it to a specific emotion class. I wanted to identify the emotion behind the words written.

It will classify into classes like -
- Anger
- Fear
- Happy
- Love
- Sad
- Surprise

Also, I plan to compare the accuracy of different models over the data set.

## Scope
This model can integrate with applications or websites which ultimately ease the review system of comments or feedback.
Limitation - As the Model predicts emotions based on the words of the sentence hence I can not identify sarcasm. 

## Timeline
Required 5 - 8 days as I am new to Machine Learning.

## Video Links or Support Links
[Data set](https://www.kaggle.com/datasets/ishantjuyal/emotions-in-text)

**Comment by Ank1taS** [comment]
Hello! @vanshsharma5503
Yes sure but can you please give me a brief idea of how would you contribute, and to what part? 
However, Let's wait for the admins to accept the proposal and assign me to it 😄

**Comment by vanshsharma5503** [comment]
@Ank1taS thanks for giving me opportunity. As I have just started with ml. So I don't have clear idea how I can ideate. If can u help me like how to start it would be really greatful.

**Comment by geyani998** [comment]
Hey @Ank1taS @vanshsharma5503 @adithya-s-k 
Could you please assign me this issue, I would follow the following steps to do this:

To classify emotions in sentences, 

    1) I will Collect labeled data: I would gather a dataset of sentences labeled with emotions like anger, fear, happy, love, sad, and surprise.

    2) Prepare the data: I will clean the sentences by removing punctuation and converting everything to lowercase, and then split the sentences into individual words to get them ready for modeling.

    3) Model Selection: I would select a machine learning model suitable for text classification, like Naive Bayes classifier, Random Forest, ANN, Multilinear perception, and many more. 

    4) I will train and evaluate the model: I would split the labeled dataset into training and testing sets. Train the model on the training data, adjusting its internal parameters to predict the correct emotion class. Finally, I will evaluate the model's performance on the testing set by calculating accuracy, precision, recall, and F1 scores. 

Please give a chance

**Comment by cluelesskid** [comment]
Hello, my name is Ishanya. I wish to contribute to this project, I like the idea behind the project,  could kindly assign me the project? Thank You
