### ISSUE TITLE
Driver Drowsiness Detection

### ISSUE THREAD

**Issue by transponster27** [CognitiveLab-tech/World-of-AI#131]
## Project Request

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | This project aims to build a safety technology for vehicles on-road that will detect if the driver’s eyes are closed for a few seconds and will alert the driver when drowsiness is detected to avoid any accidents. |
| Github | transponster27                |
| Email  | vardahrehman2002@gmail.com                                  |
| Label  |  Python, OpenCV, Imutils, Scipy, Pygame , Dlib              |

 [https://github.com/transponster27]
 
---

**Define You**

- [ ] GSSOC Participant
- Contributor

# Project Name

 Driver Drowsiness Detection

## Description

 In this project, I'll be making a Driver Drowsiness Detection System built using Python, Open CV, AND Dlib.
Since countless people drive on the highway day and night. Taxi drivers, bus drivers, truck drivers, and people traveling long-distance who suffer from lack of sleep.

Due to this, it becomes very dangerous to drive resulting in the majority of accidents happening due to the drowsiness of the driver.
So, to prevent these accidents I will build a system that will alert the driver whenever they feel sleepy.

This project aims to build a safety technology that will detect if the driver’s eyes are closed for a few seconds and will alert the driver when drowsiness is detected in order to minimize the impact and number of road accidents.

## Scope
 The project focuses on warning the drivers of any vehicle at any time of the day/night in case of drowsiness while driving. It can majorly help prevent accidents and make the driver retrieve consciousness to focus on the path properly. The requirement for this project is a web cam through which we will capture images of the vehicles along with the drivers.

## Timeline
15-06-2023 to 15-07-2023 (max)
(I'll try to wrap up the project at the earliest possible date.) 

## Video Links or Support Links

I'll update you on the videos and support links I'll be using as a reference once I get the project assigned to me.

Thank you!

**Comment by transponster27** [comment]
Please assign this project to me and allow me to contribute my hard work to GSSoC'23.

**Comment by jahnvisahni31** [comment]
Hey, I am GSSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!! and this project is already done by me as my school project 
so i can easily do this project with the necessary changes

**Comment by cluelesskid** [comment]
Hello, my name is Ishanya. I wish to contribute to this project, kindly assign me the project
