### ISSUE TITLE
[PROJECT PROPOSAL] IMDB Box Office Prediction Using Machine Learning Algorithms

### ISSUE THREAD

**Issue by AnkitaBarbora** [CognitiveLab-tech/World-of-AI#143]
## Project Request

Create a model to predict IMDb ratings of new movies based on various features, such as budget, actors, directors, writers, release year, genres, and plot. 
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | predict IMDb ratings of new movies |
| Github | AnkitaBarbora                |
| Email  |  ankitabarbora5@gmail.com                         |
| Label  | Project Request                   |

(https://github.com/AnkitaBarbora)

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Project Name

IMDB Box Office Prediction

## Description

This is a Machine Learning project that trains a model on the dataset (https://www.kaggle.com/datasets/preetviradiya/imdb-movies-ratings-details) and predicts the ratings of new movies based on various features, such as budget, actors, directors, writers, release year, genres, and plot.

## Scope

This can be useful for the film makers to for a better understanding of what they can expect from their movies.

## Timeline

I will try to complete this project within 5 days from the date assigned.

**Comment by jahnvisahni31** [comment]
Hey, I am GSSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!

**Comment by AnkitaBarbora** [comment]
@miraj0507 Please assign this issue to me.
