### ISSUE TITLE
[PROJECT PROPOSAL]:Credit Card Fraud Detection using SVM Classification

### ISSUE THREAD

**Issue by brahmamyv** [CognitiveLab-tech/World-of-AI#158]
## Project Request

Credit Card Fraud Detection by using SVM Classifier and balancing the dataset by Oversampling method.
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Detecting credit card frauds using SVM |
| Github |  Venkata Brahmam Y               |
| Email  |               venyb25@gmail.com                    |
| Label  | Python , Machine Learning ,Support Vector Machine        |

https://github.com/brahmamyv

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Project Name
Credit Card Fraud Detection

## Description
Support Vector Machines (SVM) is a popular machine learning algorithm used for credit card fraud detection. SVM is a supervised learning method that classifies data points into different categories based on their features. SVM detects the transaction is either Fraud or Legit transaction. And also data visualization is done to know more about dataset.

[Description of the project, its goals, and expected outcomes]

## Scope
SMOTE(Over Sampling) technique is used ,as credit card dataset is highly unbalanced dataset.
[The project's boundaries, including its objectives, deliverables, and constraints]

## Timeline
I need 3 days to complete the project from the date assigned.

[The project's estimated start and end dates, milestones, and deadlines for deliverables]

## Video Links or Support Links

[Links that can support the project in anyway]

**Comment by holkarjuhi1712** [comment]
Can you assign this project to me I am a contributor of gssoc'23 and I have worked on machine learning project in college assignments

**Comment by Sidhupaji-2004** [comment]
Can you assign me this project ? I have knowledge in SVM and am looking to make my contribution so as to improve the accuracy of the model. I'm a GSSOC 2023 contributor.

**Comment by brahmamyv** [comment]
@miraj0507 I cannot see my name in the leaderboard , even after the PR merged .After merging PR is there anything to do?
