### ISSUE TITLE
[UPDATE] Ai email generator

### ISSUE THREAD

**Issue by anupammaurya6767** [CognitiveLab-tech/World-of-AI#16]
Update Request: Adding Error Handling and Validation to the Code
After reviewing the existing code, I have identified the need for incorporating error handling and validation mechanisms. These additions will help improve the reliability and usability of the application, ensuring that users have a seamless experience. Here are the specific changes I propose:

OpenAI API Key Validation:

Implement a validation function to verify the format and validity of the provided OpenAI API key.
Display a warning message if an invalid or empty API key is entered.
Email Input Validation:

Introduce a validation function to check the length of the email input.
Set a maximum word limit (e.g., 700 words) and display an error message if the input exceeds the limit.
Error Handling:

Handle potential errors during API requests to OpenAI and display meaningful error messages to users.
Gracefully handle any unforeseen errors or exceptions to prevent the application from crashing or behaving unexpectedly.
By incorporating these changes, the application will provide a more robust and user-friendly experience, ensuring that users can generate accurate and formatted emails without encountering issues or unexpected errors.

I am willing to contribute to this update by working on the code changes and submitting a pull request. However, I would appreciate your guidance and feedback on the proposed approach before proceeding.

**Comment by anupammaurya6767** [comment]
@adithya-s-k 
I am GSSOC 23 contributor
I want to work on this issue
Please assign it to me

**Comment by adithya-s-k** [comment]
@anupammaurya6767 I have assigned this issue to you used GSSOC 23

you can start working on it
also can you convert  it from streamlit to gradio

**Comment by anupammaurya6767** [comment]
First of all, I have already done necessary improvements like error handling and validation.
I am going to create a pull request for the same
We can create another issue to convert it from streamlit to gradio.
is it ok?
