### ISSUE TITLE
Movie recommendation system Content-Based 

### ISSUE THREAD

**Issue by raunakcode03** [CognitiveLab-tech/World-of-AI#20]
## Project Request

---

| Field  | Machine Learning                      |
| ------ | --------------------------------- |
| About  | To recommend movie according to genre, actors or you can say that by using Content-Based filtering  with local host website |
| Github | raunakcode03-username Name-Raunak Batra               |
| Email  |    raunakbatra2003@gmail.com                               |
| Label  | Project Request                   |

# Project Name

## Description

[Description of the project, its goals, and expected outcomes]

## Scope

[The project's boundaries, including its objectives, deliverables, and constraints]

## Timeline

[As i have an experience of this project so it will take almost  4 to 7 days as i will amke some changes and will make it more attractive]

## Video Links or Support Links

[Links that can support the project in anyway]

## Sample
![Screenshot (105)](https://github.com/CognitiveLab-tech/World-of-AI/assets/127649294/08cbc948-6921-4c9d-9c0b-d9e1d21e59ae)

## Other
I have added a sample of it I will improve it and will make it more attractive and datasets will be taken  by using Kaggle. GSSOC'23 CONTRIBUTOR. @adithya-s-k  @CoginitiveLab-tech

**Comment by adithya-s-k** [comment]
@raunakcode03 
I am thrilled to receive your project request! Your idea is truly fascinating and I am eager to see it come to life.

To ensure the project runs smoothly, please follow all guidelines provided. If you are working on an AI, ML, or DL project, we kindly ask that you create a folder for your project within the respective folders and submit your progress accordingly.
Please do follow the [project readme template
](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
To ensure that everyone has a fair chance to participate, we kindly request that you complete 75% of the work within the first week of receiving the issue, and the remaining 25% within the next 3 days(10 days in total). If for any reason, you fail to meet this deadline, we will assign the task to someone else who is equally enthusiastic about contributing to this project.

If you have any questions, feel free to contact me via email or Discord or reach out to our team of project mentors.

Thank you for your contribution and let's make this project a huge success!
