### ISSUE TITLE
[PROJECT PROPOSAL] Stationary Classification

### ISSUE THREAD

**Issue by Shreyg-27** [CognitiveLab-tech/World-of-AI#206]
## Project Request

The implementation will be able to classify the different stationary items, like pen , pencil, eraser, scale etc. 

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Stationary Classification of mainly pens, pencils, scale, eraser |
| Github | Shreyg-27                  |
| Email  |          ganjooshreya5@gmail.com                         |
| Label  | GSSOC'23              |

https://github.com/Shreyg-27

---

**Define You**

- [X] GSSOC Participant
- [X] Contributor

# Project Name

Stationary Classification

## Description

The implementation will be able to distinguish between a pen, pencil scale etc. 
[Description of the project, its goals, and expected outcomes]

## Scope

To classify various stationary items.

## Timeline

August 1 2023

**Comment by Shreyg-27** [comment]
Hi @miraj0507 @adithya-s-k ! I have raised this issue under gssoc'23. Can you assign this issue to me.

**Comment by CodeitVasu** [comment]
I want to work on this issue under the gssoc'23 label. Please assign it to me
