### ISSUE TITLE
Parking Spot Occupancy Detection System

### ISSUE THREAD

**Issue by PrathmeshN99** [CognitiveLab-tech/World-of-AI#25]
## Project Request

Detect parking slot occupancy in large parking spaces, thus saving fuel and time for the drivers.

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Using Computer Vision techniques and CNN classification, detect real-time car parking occupancy |
| Github | PrathmeshN99                  |
| Email  | prathmesh99.pn@gmail.com                               |
| Label  | Project Request                   |

https://github.com/PrathmeshN99

---

- [x]  GSSOC Participant
- [x] Contributor

# Project Name

PARKING SPOT OCCUPANCY DETECTION SYSTEM

## Description

Finding a parking space nowadays becomes an issue, that is not to be neglected, it consumes time and energy. Using Computer Vision techniques and CNN classification, real-time car parking occupancy can be detected.
To develop an automated system to detect the empty parking spaces in a parking lot
To provide effective management of car parking to the users which can help in reducing the queues, improving scalability and the time required to find parking spaces

## Block diagram 

![image](https://github.com/CognitiveLab-tech/World-of-AI/assets/90515944/f17a7df9-ffe5-462f-ac82-1fa304469a98)

**Comment by PrathmeshN99** [comment]
Hey @adithya-s-k can you assign this project to me?

**Comment by sijalalyy** [comment]
i want to contribute pls assign this issue to me.

**Comment by adithya-s-k** [comment]
@PrathmeshN99 

I am thrilled to receive your project request! Your idea is truly fascinating and I am eager to see it come to life.

To ensure the project runs smoothly, please follow all guidelines provided. If you are working on an AI, ML, or DL project, we kindly ask that you create a folder for your project within the respective folders and submit your progress accordingly.
Please do follow the [project readme template
](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
To ensure that everyone has a fair chance to participate, we kindly request that you complete 75% of the work within the first week of receiving the issue, and the remaining 25% within the next 3 days(10 days in total). If for any reason, you fail to meet this deadline, we will assign the task to someone else who is equally enthusiastic about contributing to this project.

If you have any questions, feel free to contact me via email or Discord or reach out to our team of project mentors.

Thank you for your contribution and let's make this project a huge success!
