### ISSUE TITLE
GSSOC'23:Potato Disease detection

### ISSUE THREAD

**Issue by Shubhamkumar-op** [CognitiveLab-tech/World-of-AI#37]
## Project Request

This project involves using deep learning  techniques to develop an algorithm to identify the plant is infected by the disease or not
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Potato Disease Prediction Using Tensorflow |
| Github |  Shubhamkumar-op |
| Email  |                 singhshubhamkumar778@gmail.com                  |
| Label  | Project Request                   |

https://github.com/Shubhamkumar-op

---

**Define You**
I am
 [ * ] GSSOC Participant

# Plant Disease detection using CNN

## Description

- I  will use image classification using CNN  using which a farmer can take a picture it will tell you if the plant has a disease or not
- In this I will use CNN model to classify image and detect disease 

- The CNN model will be designed and trained using the collected dataset.
- Once the CNN model is trained, it will be tested using a separate set of images to evaluate its accuracy and performance.

## Scope

-  Implementing a CNN for potato disease detection aims to improve the accuracy, efficiency, and effectiveness of disease identification and management in potato farming, leading to higher crop productivity and reduced economic losses.
- After building the model woe can deploy a Mobile app so that it can be easily accessible to farmers

## Timeline

Start time: Time of Assignment
End time: July 15th.

**Comment by miraj0507** [comment]
kindly put the tick at the right place [*]

**Comment by Shubhamkumar-op** [comment]
done

**Comment by miraj0507** [comment]
[ * ]

**Comment by miraj0507** [comment]
Kindly fix the template issue and you are good to go

**Comment by Shubhamkumar-op** [comment]
done sir
