### ISSUE TITLE
[PROJECT PROPOSAL]

### ISSUE THREAD

**Issue by Shreyg-27** [CognitiveLab-tech/World-of-AI#40]
## Project Request

Book Recommendation Model - A recommendation model that would help in recommending books. 
It has 2 ways - 
Collaborative filtering 
Content based filtering 

---

| Field  | Book Recommendation System|
| ------ | --------------------------------- |
| About  | The book recommendation can be based on collabortive or content based filtering |
| Github |      Shreyg-27          |
| Email  |   ganjooshreya5@gmail.com                                 |
| Label  | GGSoC'23         |

https://github.com/Shreyg-27

---

**Define You**

- [X] GSSOC Participant
- [X] Contributor

# Project Name

Book Recommendation System 

## Description

A book recommendation system that can either be collaborative or content based. So a person should be able to recommend a book based on either if the 2 features mentioned.

## Scope

To recommend a book based on either collaborative/ content based 

## Timeline

Date of assign - August 1 2023

**Comment by adithya-s-k** [comment]
@Shreyg-27 there are already people working on a book recommendation model. Please try to submit another project proposal or try to collaborate with those projects.
