### ISSUE TITLE
House price prediction

### ISSUE THREAD

**Issue by avijit1999** [CognitiveLab-tech/World-of-AI#44]
---
name: House price prediction 
about: predict price of a house 
title: "[PROJECT PROPOSAL]"

---

## Project Request

Predice house price from given data

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | House price prediction            |
| Github | avijit1999                        |
| Email  | aec.cse.avijitmandal@gmail.com    |
| Label  | Project Request                   |

https://github.com/avijit1999
---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Project Name

House Prices prediction 

## Description

Here I want to develop a model to predict price of house using some data.
## Scope
It is limited only data. It can mordify to webapp where user can enter the informations using keyboard.

## Timeline

End Date: as soon as possible(after assigned it to me)

**Comment by avijit1999** [comment]
Hay @adithya-s-k please give me a chance to work on it

**Comment by adithya-s-k** [comment]
@avijit1999 
I am thrilled to receive your project request! Your idea is truly fascinating and I am eager to see it come to life.

To ensure the project runs smoothly, please follow all guidelines provided. If you are working on an AI, ML, or DL project, we kindly ask that you create a folder for your project within the respective folders and submit your progress accordingly.
Please do follow the [project readme template
](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
To ensure that everyone has a fair chance to participate, we kindly request that you complete 75% of the work within the first week of receiving the issue, and the remaining 25% within the next 3 days(10 days in total). If for any reason, you fail to meet this deadline, we will assign the task to someone else who is equally enthusiastic about contributing to this project.

If you have any questions, feel free to contact me via email or Discord or reach out to our team of project mentors.

Thank you for your contribution and let's make this project a huge success!
