### ISSUE TITLE
Car Fuel Consumption Prediction

### ISSUE THREAD

**Issue by Praneesh-Sharma** [CognitiveLab-tech/World-of-AI#54]
## Project Request

A machine learning model that predicts the fuel consumption of a car.
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | This is a project in Machine Learning, where the model will predict the fuel consumption of a car based on the given parameters. This model will be hosted on Streamlit. |
| Github | Praneesh-Sharma |
| Email  |pegasus30042004@gmail.com |
| Label  | Project Request for GSSoC'23                   |

#### GitHub:  https://github.com/Praneesh-Sharma
---

**Define You**

- [✔️ ] GSSOC Participant
- [ ✔️] Contributor

# Project Name

Fuel Consumption Prediction

## Description

Gives the user the amount of fuel (in gallons) consumed by a car. The parameters to be entered by the user will be Cylinders, Displacement, Horsepower, Weight, Acceleration and Model Year. The output will be the miles covered per gallon.

## Scope

This model will help the user decide on which car is more economical and which cars to consider while deciding to buy a car. 

## Timeline

Start Date: Date of Project Assignment
End Date: 1 week from Start Date

**Comment by Praneesh-Sharma** [comment]
I would like to work on this issue. Could you please assign it to me. @adithya-s-k

**Comment by adithya-s-k** [comment]
@Praneesh-Sharma 
I am thrilled to receive your project request! Your idea is truly fascinating and I am eager to see it come to life.

To ensure the project runs smoothly, please follow all guidelines provided. If you are working on an AI, ML, or DL project, we kindly ask that you create a folder for your project within the respective folders and submit your progress accordingly.
Please do follow the [project readme template
](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
To ensure that everyone has a fair chance to participate, we kindly request that you complete 75% of the work within the first week of receiving the issue, and the remaining 25% within the next 3 days(10 days in total). If for any reason, you fail to meet this deadline, we will assign the task to someone else who is equally enthusiastic about contributing to this project.

If you have any questions, feel free to contact me via email or Discord or reach out to our team of project mentors.

Thank you for your contribution and let's make this project a huge success!
