### ISSUE TITLE
Classroom Activity Detection 

### ISSUE THREAD

**Issue by Rishi-11-2** [CognitiveLab-tech/World-of-AI#59]
Problem Statement : To recognize classroom activities . I propose a Machine Learning model that can recognize activities inside a classroom from the Dataset that is collected online

**Comment by miraj0507** [comment]
kindly follow the template and propose your issue 
Please do follow the [project readme template](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
