### ISSUE TITLE
adding tech stack badges in readme

### ISSUE THREAD

**Issue by mridulsaggi** [CognitiveLab-tech/World-of-AI#61]
i would like to add tech stack badges and shields in readme . it makes the readme look more pretty and give better information about the technologies used.
please assign me this issue as gssoc contribution
example:
![image](https://github.com/CognitiveLab-tech/World-of-AI/assets/91930535/48f79a2e-ea41-4b34-912d-36f25e2bc79e)

**Comment by miraj0507** [comment]
kindly follow the template and propose your issue
Please do follow the [project readme template](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)
