### ISSUE TITLE
Cricket Score Predictor

### ISSUE THREAD

**Issue by Shreyg-27** [CognitiveLab-tech/World-of-AI#62]
## Project Request

T20 - Cricket score predictor. 

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | The model will be able to predict the cricket score on the basis of the available dataset, and various input fields like the batting and bowling teams, the wickets taken, the city, the overs left,etc. |
| Github | Shreyg-27                  |
| Email  |            ganjooshreya5@gmail.com                       |
| Label  | GSSoC'23                  |

https://github.com/Shreyg-27
---

**Define You**

- [X] GSSOC Participant
- [X] Contributor

# Project Name
Cricket Score Predictor

## Description

The aim of this project is to work on the prediction of T20 Cricket scores. 

## Scope

So, the input would select the batting team, bowling team, the current city, the score, overs left, wickets were taken, and runs scored in the recent overs.  Accordingly, output would be created. An application would be created using Streamlit, that would help in predicting the score.  

## Timeline

Till 1 August.

**Comment by Shreyg-27** [comment]
Hi @adithya-s-k! I have raised this issue! Can you please assign this to me under the GSSoC'23 ?

**Comment by miraj0507** [comment]
Hi, @Shreyg-27 , kindly fix the heading [Project Proporsal], write your topic there, I would then assign the same to you

**Comment by Shreyg-27** [comment]
> Hi, @Shreyg-27 , kindly fix the heading [Project Proporsal], write your topic there, I would then assign the same to you

@miraj0507 I have made the change.
