### ISSUE TITLE
Adding hover effect on the buttons[UPDATE]

### ISSUE THREAD

**Issue by akankshachanana1** [CognitiveLab-tech/World-of-AI#70]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | I want to add hover effect on buttons |
| Github | akankshachanana1 |
| Email  |  akankshachanana05@gmail.com   |
| Label  | Update request                    |

https://github.com/akankshachanana1

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Currently the buttons are not interactive 

**Describe the solution you'd like...**

I want to make them interactive by adding the hover effect (by adding gradient effect or by increasing its size or by adding a border shadow or neon effect).

**Comment by Mimi97-aqua** [comment]
Hi
I would like to work on this. Please can you assign it to me?

**Comment by adithya-s-k** [comment]
@akankshachanana1 please create issue in the scope of this particular repository
