### ISSUE TITLE
Contact us form is missing placeholder[UPDATE]

### ISSUE THREAD

**Issue by HimanshuNarware** [CognitiveLab-tech/World-of-AI#71]
##Description

I want to add a placeholder in the contact us form, it will improve the readability of the website.

| Field  |                                                                                                         Description                                                |
| ------ |  |
| About  | contact form does not contain any placeholder I want to work on this issue, I want to add a placeholder in the contact us form      |
| Github | Your HimanshuNarware   |
| Email  |himanshunarware77@gmail.com                     |
| Label  | Update request                    |

https://github.com/HimanshuNarware?tab=stars

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

##screenshot
![101](https://github.com/CognitiveLab-tech/World-of-AI/assets/83147410/33b6d27f-9c37-4e23-9e1e-7dfd884f3e7f)

**Comment by adithya-s-k** [comment]
@HimanshuNarware please create issues only in the scope of this repository which is AI ML DL related
