### ISSUE TITLE
Sentiment Analysis Using NLP

### ISSUE THREAD

**Issue by Juhibhojani** [CognitiveLab-tech/World-of-AI#77]
## Project Request

Sentiment Analysis: I want to perform sentiment analysis using machine learning algorithms.
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Using the Dataset available on Kaggle, I want to classify each text into positive, negative, and neutral! |
| Github | Juhibhojani               |
| Email  |   juhibhojani03@gmail.com   |
| Label  | Project Request     |

Github Profile Link : https://github.com/Juhibhojani
---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Sentiment Analysis

## Description

Using Machine Learning Algorithms, I would like to predict the nature of text description. This project will use Word Embedding techniques and text cleaning processes in order to predict class labels using classification algorithms and hence serve as a base to start with NLP

## Scope

Objective: Getting started with NLP, Learning Word Embedding techniques, and applying appropriate classification algorithms.

Deliverables: A jupyter notebook file along with the necessary explanation and dataset 

## Timeline

Over a period of 7-10 Days, a good accuracy result can be delivered.

## Video Links or Support Links

I will be using the following resources for this project:
1) Kaggle
2) Medium | towards data science and others

**Comment by miraj0507** [comment]
Kindly fix the template @Juhibhojani  , [ * ] creates a tick follow it
