### ISSUE TITLE
[UPDATE] Adding margin on the contact section and improving the scroll effect 

### ISSUE THREAD

**Issue by nitin-pandita** [CognitiveLab-tech/World-of-AI#84]
![image](https://github.com/CognitiveLab-tech/World-of-AI/assets/91310284/9484d239-e8d5-40db-8a88-42d67c9658ec)

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | The contact section is going out of the screen and needs to add some margin to it and needs to improve the scroll effect |
| Github | nitin-pandita                |
| Email  |  mr.nitinpandita@gmail.com                                 |
| Label  | Update request                    |

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

**Additional context**

**Comment by nitin-pandita** [comment]
I would like to work on it

**Comment by adithya-s-k** [comment]
@nitin-pandita the website isnt part of the OSS repo.
please create issue with respect to only AI ML and DL
Thank you
