### ISSUE TITLE
Early Heart disease prediction using ML

### ISSUE THREAD

**Issue by poorvika11** [CognitiveLab-tech/World-of-AI#9]
## Project Request

Developing a model to predict early heart disease prediction by doing a comparitive analysis of different machine learning models to predcit heart disease with highest accuracy on defined and most important attributes

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Early Heart disease prediction using ML |
| Github | poorvika11                  |
| Email  |        poorvikagupta2001@gmail.com                           |
| Label  | Project Request                   |

 https://github.com/poorvika11

---

**Define You**

- GSSOC Participant
- Contributor

# Early Heart Disease Prediction

## Description

The project involved analysis of the heart disease patient dataset with proper data processing. Then, different models will be trained and predictions will be made with different algorithms KNN, Decision Tree, Random Forest,SVM,Logistic Regression etc. Variety of Machine Learning algorithms implemented in Python to predict the presence of heart disease in a patient. This is a classification problem, with input features as a variety of parameters, and the target variable as a binary variable, predicting whether heart disease is present or not.

## Scope
Objectives:

- Implement a robust and efficient heart disease prediction.
- Enable high accuracy model using comparitive analysisof all machine learning models.

Deliverables

- A trained model capable of predciting disease accurately.
- Well-documented guidelines, including dataset preparation, training, inference,exploratory data analysis and any specific requirements.
- Models predicting using different algorithms KNN, Decision Tree, Random Forest,SVM,Logistic Regression etc.

## Timeline

Start Date: when assigned
End Date: 10 August

**Comment by Jyotsna1304** [comment]
Hello, I'm a GSSoC'23 contributor. I would like to work on this project. Can you please assign me. I will implement a robust prediction and enable high accuracy.

**Comment by sadhana70** [comment]
I'm a GSSoC'23 contributor. Please, assign the issue to me.

**Comment by adithya-s-k** [comment]
@poorvika11  I have assigned this particular project to you under GSSOC 23.
Will you be able to manage the project alone or would you like to collaborate with other contributors

All the best contributing
if you have any doubts on the project structure feel free to contact me

**Comment by Veena4512** [comment]
Hello, I'm a GSSoC'23 contributor. I love  to work on this project. if there is any chance I can collaborate .

**Comment by poorvika11** [comment]
@adithya-s-k please label it with level label also. Highly requested to you to do this
