### ISSUE TITLE
Multiple disease prediction web app 

### ISSUE THREAD

**Issue by Shubhamkumar-op** [CognitiveLab-tech/World-of-AI#91]
## Project Request

Disease prediction app using various machine learning algorithm where we can find if a person is suffering from disease or not

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Disease prediction web app |
| Github |  Shubhamkumar-op                 |
| Email  |              singhshubhamkumar778@gmail.com](mailto:singhshubhamkumar778@gmail.com                     |
| Label  | Project Request                   |

https://github.com/Shubhamkumar-op

---

**Define You**

- [ * ] GSSOC Participant
- [ * ] Contributor

# Project Name

Multiple disease prediction app

## Description

- I will make a disease prediction web app that will tell you the if you have that disease or not 
- In this we will use multiple ML algorithm 
- This web app predict  disease like heart disease, diabetes, parkinnson's

## Scope

After using machine learning algorithm like logistic regression , SVM  we will improve the model performance 
Them we will use stream lit cloud to deploy our app from where user fill the required values and app will tell whether it  suffering from that disease or not

## Timeline

Start time: Time of Assignment
End time: July 25th.

**Comment by NiShITa-code** [comment]
Hey I have been working on something similar please assign this project to me
