### ISSUE TITLE
[PROJECT PROPOSAL]

### ISSUE THREAD

**Issue by smty2018** [CognitiveLab-tech/World-of-AI#97]
## Project Request

---

| Machine Learning  | Breast Cancer Detection                 |
| ------ | --------------------------------- |
|  A short Description about the project | It is an important application in the field of medical diagnostics. Here's a high-level overview of how you can approach building a breast cancer detection system |
| Github | smty2018                 |
| Email  |   sheetalimaity2003@gmail.com                             |
| Label  | Project Request                   |

<https://github.com/smty2018>

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Project Name

Breast Cancer Detection

## Description

A Logistic Regression Based Model to detect Breast Cancer

## Timeline

Start: As soon as the issue is assigned
Duration: 2 days (Maximum)

## Video Links or Support Links

[Links that can support the project in anyway]

**Comment by smty2018** [comment]
@adithya-s-k please assign me this issue

**Comment by adithya-s-k** [comment]
@smty2018 please follow the [project request template](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)

**Comment by smty2018** [comment]
@adithya-s-k I have updated according to the project template. Now please assign me this issue.
