### ISSUE TITLE
Add the black linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [CognitiveLab-tech/World-of-AI#98]
## Project Request

Add the black linter to ensure proper and uniform linting of the codebase.

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | Add the black linter workflow to ensure proper linting of the codebase. |
| Github | metabiswadeep                |
| Email  |                                   |
| Label  | Project Request                   |

https://github.com/metabiswadeep

---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Project Name
Add the black linter workflow.

## Description
Add the black linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

[Description of the project, its goals, and expected outcomes]

## Scope
To maintain proper and uniform linting of code through the entire repository.

**Comment by adithya-s-k** [comment]
@metabiswadeep how much time will you take to create the PR
this would help the repository a lot
so let me know as soon as possible

**Comment by metabiswadeep** [comment]
> @metabiswadeep how much time will you take to create the PR
> this would help the repository a lot
> so let me know as soon as possible

I can make the PR in 1 day.

**Comment by metabiswadeep** [comment]
@adithya-s-k

**Comment by metabiswadeep** [comment]
@adithya-s-k I have now prepared my branch with the linter, and will be able to make the PR as soon as you assign the issue to me.

**Comment by metabiswadeep** [comment]
@adithya-s-k Could you assign me the issue
